### PR TITLE
Change CHANGELOG.md to 'Keep a changelog' format

### PR DESCRIPTION
**Pull request by siccovansas**
It would be awesome if the current changelog format is changed to the '[Keep a changelog](https://keepachangelog.com/en/1.0.0/)' format. [Nextcloud recommends this](https://nextcloudappstore.readthedocs.io/en/latest/developer.html#changelog) for its apps. A benefit is that the entry of the most recent version is shown in the 'Apps' section of a Nextcloud installation. This makes it easy for admins to see what's new :) (now you need to visit this GitHub repo and find the CHANGELOG.md file in order to see what's new)!

Besides this change the CHANGELOG.md file still needs to be moves from `keeweb/CHANGELOG.md` to the top level folder.

Thanks everyone for creating and maintaining this awesome Nextcloud app :)!

### CODE REVIEW

**Comment by arnowelzel** [comment]
Sorry for the delay in reviewing this, but this makes really sense - thanks

**Comment by arnowelzel** [comment]
It seem, this breaks the release workflow :-(

**Comment by arnowelzel** [comment]
I reverted the changelog to keep the release workflow working and getting the app released. I have to check with @jhass how the changelog is parsed in the release workflow before we change the changelog.

**Comment by siccovansas** [comment]
@arnowelzel thanks for the update! Sorry for breaking the release workflow, I didn't know it depended on the changelog :)

**Pull request merged**
