### PR TITLE
Bump max-version to 14 and fix css width

### PR DESCRIPTION
**Pull request by myxor**
With this PR keeweb is again working on Nextcloud 14.
It includes the max-version increasing to 14 and the css fix meantioned in https://github.com/jhass/nextcloud-keeweb/issues/67#issuecomment-425037641.

### CODE REVIEW

**Comment by jhass** [comment]
See https://github.com/jhass/nextcloud-keeweb/issues/67#issuecomment-355331757

**Comment by e-alfred** [comment]
@jhass You could at least merge the changes so people installing from the repository have a working app in the meantime.

**Comment by ravermeister** [comment]
can we expect a Keeweb version for NC14 in the near future?

**Comment by jhass** [comment]
Superseded by #81 

Thanks!

**Pull request closed without merging**
