### PR TITLE
Nextcloud 17

### PR DESCRIPTION
**Pull request by PriceChild**

### CODE REVIEW

**Comment by e-alfred** [comment]
@jhass Can you publish a new release on the App Store for Nextcloud 17?

**Comment by nilsjor** [comment]
I second this, it recently installed a fresh v17, and it would be great installing from the app store!

**Comment by BjoernLudwigPTB** [comment]
> @jhass Can you publish a new release on the App Store for Nextcloud 17?

Is this change really all that's needed? Then I would so much love to see it is merged!

@jhass If there is something more to do, could you give a hint on how to tackle open issues with Nextcloud 17?

**Comment by bobpaul** [comment]
I'm running Nextcloud 17 and I just installed this from the appstore (I had to click "Enable Untested Apps and Download"). It seems to work fine. So I do believe the above is all that's needed to make it officially support NC17

**Comment by jhass** [comment]
I'm hesitant to release an update due to the overall brokenness of the addon.

**Comment by ApertureDevelopment** [comment]
What exactly is broken? I am using the addon since months now and didn't had any issue so far

**Comment by PriceChild** [comment]
@jhass the addon works for me, what issues are you seeing?

**Comment by jhass** [comment]
Lots of people are, just have a look through the open issues.

**Comment by eloo** [comment]
but isn't this only affecting the "clicking" on the file? 
For all other cases your plugin is working pretty good.
and also the opening of the file can be fixed with one of the numerous workarounds here. maybe adding one of it to the description would be fine.

**Comment by jhass** [comment]
"all the other cases" don't need any integration of this into nextcloud at all, just use https://app.keeweb.info

**Comment by PriceChild** [comment]
> Lots of people are having trouble, just have a look through the open issues. It boils down to Nextcloud not having a proper API for addons to add and handle custom mimetypes.

Aha ok, thanks.

This is quite surprising me as I'm not able to reproduce any of the issues I've looked at so far, running on 17.0.1

Many of them also seem to be raised against 16, which the plugin was already marked as compatible with?

Either way it doesn't matter to me, it's easy enough to force the app enabled.

**Comment by thrdroom** [comment]
> "all the other cases" don't need any integration of this into nextcloud at all, just use https://app.keeweb.info

> Lots of people are having trouble, just have a look through the open issues. It boils down to Nextcloud not having a proper API for addons to add and handle custom mimetypes.

@jhass 

WTF?! Its been like more than two years since i followed this project, and it seems like you haven't progressed that much since then. Then just search for a new maintainer and handover this project to someone else who really cares and who wants to help the people, cause you don't seem to care really! Even when people are doing PRs to do your work, you are still acting annoying. And suggesting an online-service hosted by an unknown third party to someone who wants to host it in their own cloud is really a slap in the face.

I mean like yeah, i get it...its fucked up that nextcloud still dont has a proper API for addons and custom mimetypes. But geez, then stop acting like "i can't do nothing about it" and start giving people a real help and some detailed workarounds. I can operate fine with the workarounds provided across the multiple issue threads here, but its a pain in the ass to find them, so lets change that. Some prominent install and workaround instructions on the github and addon store page would be a good start. A release for Nextcoud 17 would be next good thing to do. Things will never be perfect so instead of just playing the waiting game lets find some compromise we all can live with. And if you dont have the time, energie or love for this project anymore then please just pass it to someone else who does, cause this project needs some passion ;-)

thanks

**Comment by jhass** [comment]
@thrdroom and what exactly makes you entitled to receiving my work? 

The "help wanted" labels on the issues are no joke, I'm looking forward to your pull request. You'll find I'm still quite responsive on those!

**Comment by TitanSpirit** [comment]
@jhass So far I did not experience any issues with your addon. I am grateful for your efforts, really love it!
Mimetypes? Just logged in via ssh to my server and set it as you described. I love your integration with nextcloud. I do not want to use not selfhosted keeweb :) so your solution wins.

**Pull request closed without merging**
