### PR TITLE
Fixed Keeweb application for NC 28.x.x

### LINKED ISSUE #229: Internal server error
Hi!

When opening keeweb in NC28RC, I got an internal server error.

This should be the relevant log:

`{"reqId":"TaQzngMHMg5YWUCpkleC","level":3,"time":"2023-12-09T16:46:54+01:00","remoteAddr":"10.20.0.2","user":"xxx",
"app":"index","method":"GET","url":"/apps/keeweb/","message":"Call to undefined method OCP\\AppFramework\\Http\\EmptyCo
ntentSecurityPolicy::allowInlineScript() in file '/var/www/nextcloud/apps/keeweb/lib/Controller/PageController.php' lin
e 143","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0","version":"28.0.0.8","excep
tion":{"Exception":"Exception","Message":"Call to undefined method OCP\\AppFramework\\Http\\EmptyContentSecurityPolicy:
:allowInlineScript() in file '/var/www/nextcloud/apps/keeweb/lib/Controller/PageController.php' line 143","Code":0,"Tra
ce":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFra
mework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":
"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"m
atch","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleReque
st","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Pre
vious":{"Exception":"Error","Message":"Call to undefined method OCP\\AppFramework\\Http\\EmptyContentSecurityPolicy::al
lowInlineScript()","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/keeweb/lib/Controller/PageController.php","line":
56,"function":"getCSP","class":"OCA\\Keeweb\\Controller\\PageController","type":"->"},{"file":"/var/www/nextcloud/lib/p
rivate/AppFramework/Http/Dispatcher.php","line":230,"function":"index","class":"OCA\\Keeweb\\Controller\\PageController
","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"execute
Controller","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramew
ork/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/w
ww/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework

\\App","type":"::"},{"
file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file"
:"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcl
oud/apps/keeweb/lib/Controller/PageController.php","Line":143},"message":"Call to undefined method OCP\\AppFramework\\H
ttp\\EmptyContentSecurityPolicy::allowInlineScript() in file '/var/www/nextcloud/apps/keeweb/lib/Controller/PageControl
ler.php' line 143","exception":{},"CustomMessage":"Call to undefined method OCP\\AppFramework\\Http\\EmptyContentSecuri
tyPolicy::allowInlineScript() in file '/var/www/nextcloud/apps/keeweb/lib/Controller/PageController.php' line 143"}}`

Additional Info:

**Desktop (please complete the following information):**
 - OS: OpenSuse TW
 - Browser: Firefox
 - Version: 120

**Server (please complete the following information):**
 - OS: ubuntu 22.04
 - HTTP server: nginx version: nginx/1.25.3
 - Database: mysql  Ver 15.1 Distrib 10.6.12-MariaDB
 - PHP version: Copyright (c) The PHP Group/Zend Engine v4.1.25, Copyright (c) Zend Technologies   with Zend OPcache v8.1.25, Copyright (c), by Zend Technologies
 - Nextcloud version: 28RC
 - Bookmarks app version: 13.1.1
 - Activated Nextcloud Apps: Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bookmarks: 13.1.1
  - breezedark: 27.0.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.0-rc.2
  - contactsinteraction: 1.9.0
  - cospend: 1.5.12
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.0-beta.4
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - integration_openai: 1.1.5
  - keeweb: 0.6.13
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - music: 1.9.1
  - news: 25.0.0-alpha2
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recognize: 6.0.1
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.0-beta.1
  - richdocumentscode: 23.5.602
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - spreed: 18.0.0-rc.3
  - support: 1.11.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - audioplayer: 3.4.0 (installed 3.4.0)
  - circles: 28.0.0-dev (installed 25.0.0)
  - documentserver_community: 0.1.13 (installed 0.1.13)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.9.0)
  - libresign: 7.1.1 (installed 7.1.1)
  - survey_client: 1.16.0 (installed 1.8.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - unsplash: 2.2.1 (installed 2.2.1)
  - user_ldap: 1.19.0
  - workflow_pdf_converter: 1.12.0 (installed 1.12.0)
 - Nextcloud configuration: 
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "vmd64337.contaboserver.net",
            "luckyshadows.net",
            "power.ddnss.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.0.8",
        "overwrite.cli.url": "https:\/\/vmd64337.contaboserver.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "log_rotate_size": 104857600,
        "logfile": "\/daten\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Freigaben",
        "skeletondirectory": "",
        "trashbin_retention_obligation": "auto, 7",
        "app_install_overwrite": [
            "keeweb",
            "deck",
            "spreed",
            "bookmarks",
            "music",
            "unsplash",
            "onlyoffice",
            "breezedark",
            "documentserver_community",
            "bruteforcesettings",
            "news",
            "riotchat"
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "beta",
        "default_phone_region": "DE",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Web server error log**
```
nothing relevant (afaik)
```

Please advice, what information you/we might need to solve this issue, happy to help.

### PR DESCRIPTION
**Pull request by florian-forestier**
Hi,

This MR aim to fix #229 and #230.

The most important part of this MR is the `viewer.js` file. As Nextcloud removed the `OCA.Files` API, I had to use the new one. The original problem (CORS issue) was solved by adding `$csp->addAllowedScriptDomain("'unsafe-inline'");` to `lib/Controller/PageController.php`. Tested on Nextcloud 28.0.1.

I also seen #221. Please note that I am interested in continuing your work on this Nextcloud plugin, as I use it on a daily basis, for personal and professional use.

I also also take the opportunity of this PR to thank you for the job you've done over the years on this project, having access to my keepass files directly on my Nextcloud saved me several times :smile: 

_Note: don't be affraid of the `+6,515` added lines, 99.9% of them are in the `package-lock.json` file..._

:wave:

### CODE REVIEW

**Comment by arnowelzel** [comment]
Thanks for your help, great!

Did you check, if that version still works with NC 27 as well? If not, we need to increase the minimum supported version to 28 as well and keep the older version for NC 27 and below unchanged.

**Comment by florian-forestier** [comment]
Hi,

It partially works for NC 27 (file association is broken due to changes in `viewer.js`). It would be better to increase the minimum supported version.

**Comment by arnowelzel** [comment]
> Hi,
> 
> It partially works for NC 27 (file association is broken due to changes in `viewer.js`). It would be better to increase the minimum supported version.

Ok, thanks for the feedback. I'll change the supported version since NC 27 is still maintained and the older version works fine there.

**Comment by arnowelzel** [comment]
Hmm - it does not work here with NC 28 either :-(

Clicking a KDBX file will open Keeweb - but the file is not opened then.

**Comment by florian-forestier** [comment]
Looking on it, I didn't had this problem on my previous test

**Comment by arnowelzel** [comment]
May it helps to know, that my server responds with HTTP 404 to the request, eventhough the file exists:

image

image

**Comment by florian-forestier** [comment]
Okay, it seems there is two issues:
* First of all, Keeweb could not load some content because of CSP (again). There is a missing `addAllowedScriptDomain("blob:");`. I don't know why this error appears only now.
* Secondly, it seems that Nextcloud servers which are not configured to enforce HTTPS (without `overwriteprotocol` in `config.php`) experience some issues loading files. As HTTPS is required to make Keeweb works, the simple (but working) solution is to change all HTTP calls to HTTPS in the PageController.php file.

The following patch should solve these issues:

```diff
diff --git a/keeweb/lib/Controller/PageController.php b/keeweb/lib/Controller/PageController.php
index 005ced5..847afac 100644
--- a/keeweb/lib/Controller/PageController.php
+++ b/keeweb/lib/Controller/PageController.php
@@ -87,6 +87,7 @@ class PageController extends Controller {
 	public function config($file) {
 		$csrfToken = \OC::$server->getCSRFTokenManager()->getToken()->getEncryptedValue();
 		$webdavBase = \OCP\Util::linkToRemote('webdav');
+        $webdavBase = str_replace("http://", "https://", $webdavBase);
 		$config = ['settings' => (object) null];
 		if (isset($file)) {
 			$config['files'] = [
@@ -136,6 +137,7 @@ class PageController extends Controller {
 		$csp->addAllowedConnectDomain("'self'");
 		$csp->addAllowedConnectDomain('https://services.keeweb.info');
 		$csp->addAllowedScriptDomain('https://plugins.keeweb.info');
+        $csp->addAllowedScriptDomain("blob:");
 		$csp->addAllowedScriptDomain("'unsafe-inline'");
 		$csp->addAllowedConnectDomain('https://plugins.keeweb.info');
         $csp->allowEvalScript(true);
```

Tested on a fresh NC28 install. @arnowelzel can you try on your side and confirm ?

**Comment by arnowelzel** [comment]
Sorry - still does not work here. Same effect: KeeWeb is loaded but does not open the file. Server is using HTTPS (as it was before).

Same error in the console:

```
GET https://myserver.example/apps/keeweb/?open=/test.kdbx 404 (Not Found)
```

About this line - I don't think we need that. When the instance is not using HTTPS the resource can not be loaded anyway, since it will not be available using HTTPS:

```
$webdavBase = str_replace("http://", "https://", $webdavBase);
```

**Comment by florian-forestier** [comment]
I can't reproduce from my side on a fresh and a old Nextcloud server, using Firefox 115.6.0esr (normal & private browsing), and Chromium 120.0.6099.129 (normal & private browsing)... Also checked using Chrome and Brave on mobile (last version available on Play Store) without issue.

My server is deployed using the official docker image, with a Traefik acting as reverse-proxy. Can you give more information on how your Nextcloud is deployed, so I could create the same environment to check ?

**Comment by arnowelzel** [comment]
I don't use Docker but a plain server setup with NC 28 using Apache 2.4, PHP-FPM 8.3 and MariaDB.

To be sure I repeated the test with a fresh setup - and now it works. The replacement of http with https is not needed since KeeWeb would not work when loaded via HTTP anyway.

I will apply the change `$csp->addAllowedScriptDomain("blob:");` and then prepare a new release.

**Comment by arnowelzel** [comment]
Now the release action does not work any longer :-(.

``` 
bin/release: line 65: hub: command not found
Error: Process completed with exit code 127.
```

@jhass Can you have a look what is missing? I can't update the workflow actions, just trigger them.

**Comment by jhass** [comment]
Github deprecated `hub` in favor of `gh` a while ago, I guess they removed the former from the GHA runner images now. I fixed the release script to use `gh` over `hub`.

Thanks guys!

**Comment by arnowelzel** [comment]
Thanks for the quick response and help!

**Comment by bkraul** [comment]
@florian-forestier is da real MVP. Thank you for this!

**Pull request merged**
