### PR TITLE
fix service worker caching

### PR DESCRIPTION
**Pull request by HolgerHees**
is fixing https://github.com/jhass/nextcloud-keeweb/issues/137

### CODE REVIEW

**Comment by maurerle** [comment]
@HolgerHees can you describe a little more what is not working without the fix and why the fix is needed?

Do you think that the caching issue in #150 is related to this?

**Comment by HolgerHees** [comment]
the main problem is that we should cache only the huge keeweb config file itself. Everything else comes from nextcloud and can contain session token which should never be cached.

**Comment by maurerle** [comment]
This is quite clear, but is there a caching error which can be observed or some way to test this?
Currently I can only say that this patch does not break anything obviously :)

**Comment by HolgerHees** [comment]
it happens for me with the following scenario.

the first time I click on a keypass file inside nextcloud which will directly opened with the keyweb app.

next time (e.g. the next day when the token is expired) I go directly to the keyweb app, without clicking on the keypass file In this case my previous opened keypass file is preselected/prefilled. But I'm not able to open it, because the keyweb app is still using expired tokens.

**Comment by maurerle** [comment]
And with the fix the previous file is still preselected but only while the token is valid?

**Comment by HolgerHees** [comment]
yes. it is still preselected and the tokens are refreshed because the page
which contains the fresh token is not cached anymore.

maurerle <notifications@github.com> schrieb am Fr., 3. Juli 2020, 16:33:

**Comment by HolgerHees** [comment]
to explain the problem a little bit more detailed.

beginning of the year I implemented a fix to update session tokens on preselected keypass files coming from local storage

https://github.com/jhass/nextcloud-keeweb/pull/128/files

this fix is using the javascript variable OC.requestToken to update outdated token which are stored as part of the keypass file url. This variable is initialized from an attribute stored in the head tag of the nextcloud html page (top frame).

if the keyweb app is now caching everything, it will also cache the nextcloud html page which results in a cached session token and this means that the variable OC.requestToken always contains a outdated token too.

so, my initial fix will never work.

**Comment by maurerle** [comment]
Oh okay, thank you. Then I think this should get merged too @jhass . I tested it and it works so far.

**Comment by jhass** [comment]
Okay, I hope  upstream doesn't iterate to much and the patch stays that simple.  If not we might want to just maintain our own version and overwrite it.

**Pull request merged**
