### PR TITLE
Bump max nextcloud version to 13

### PR DESCRIPTION
**Pull request by nougad**
Nextcloud 13 beta 3 is already out: https://nextcloud.com/blog/nextcloud-13-beta-3-ready-for-your-testing-go-and-win-a-t-shirt/

see #67

### CODE REVIEW

**Comment by eloo** [comment]
can this please be merged soon? its odd to use the xml workaround :/

**Comment by jhass** [comment]
See #67

**Comment by danger89** [comment]
Duplicate of already open PR: https://github.com/jhass/nextcloud-keeweb/pull/81

**Comment by jhass** [comment]
Closing in favor of #81

**Pull request closed without merging**
